# Generated by Django 5.2.5 on 2025-08-27 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traveloption',
            options={'ordering': ['date_time']},
        ),
    ]
